## Importação da biblioteca pandas

In [1]:
import pandas as pd

## Convertendo o dataset tsv para csv

In [2]:
import csv
with open('../09-pandas/datasets/2004-2021.tsv', 'r') as entrada, open('../09-pandas/datasets/2004-2021.csv', 'w', newline='') as saida:
    escrever = csv.writer(saida)
    for row in csv.reader(entrada, delimiter='\t'):
        escrever.writerow(row)

## Importando o Dataset

In [3]:
# carregando dataset com separador sep =','
data = pd.read_csv('../09-pandas/datasets/2004-2021.csv',sep=',')

In [4]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0

## Mostrando as primeiras linhas do Dataset

In [5]:
## mostras as 10 primeiras linhas do dataframe
data.head(10)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082
5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,0.999,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134
6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,1.030,1.950,0.353,0.150,1.1,0.068,0.7332,1.294,0.062
7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,1.350,2.000,0.515,0.097,1.116,0.091,0.9923,1.36183,0.082
8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,1.100,1.699,0.353,0.101,0.931,0.072,0.7577,1.2972,0.077
9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,0.989,1.700,0.277,0.115,0.947,0.091,0.5643,1.3541,0.096

## Informações gerais sobre o Dataset

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 120823 entries, 0 to 120822
Data columns (total 18 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   DATA INICIAL                   120823 non-null  str
 1   DATA FINAL                     120823 non-null  str
 2   REGIÃO                         120823 non-null  str
 3   ESTADO                         120823 non-null  str
 4   PRODUTO                        120823 non-null  str
 5   NÚMERO DE POSTOS PESQUISADOS   120823 non-null  int64
 6   UNIDADE DE MEDIDA              120823 non-null  str
 7   PREÇO MÉDIO REVENDA            120823 non-null  float64
 8   DESVIO PADRÃO REVENDA          120823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           120823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           120823 non-null  float64
 11  MARGEM MÉDIA REVENDA           120823 non-null  str
 12  COEF DE VARIAÇÃO REVENDA       120823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO       120823 non-null  str
 14  DESVIO PADRÃO DISTRIBUIÇÃO     120823 non-null  str
 15  PREÇO MÍNIMO DISTRIBUIÇÃO      120823 non-null  str
 16  PREÇO MÁXIMO DISTRIBUIÇÃO      120823 non-null  str
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO  120823 non-null  str
dtypes: float64(5), int64(1), str(12)
memory usage: 16.6 MB

## Data Frame

In [7]:
type(data)

pandas.DataFrame

### podemos acessar as **dimensões do Data Frame** utilizando o atributo .shape do Data Frame

In [48]:
data.shape

(120823, 19)

In [9]:
print(f'O DataFrame possui {data.shape[0]} linhas/observações/registros e {data.shape[1]} colunas/atributos/variáveis.')

O DataFrame possui 120823 linhas/observações/registros e 18 colunas/atributos/variáveis.

## Criando um DataFrame

Um novo DataFrame pode ser criado a partir de um dicionário, onde cada chave possui uma linha de elementos de igual tamanho.
    As chaves representam as colunas e cada um dos valores de sua lista representa o valor da linha correspondente para aquela coluna.

In [49]:
personagens_df = pd.DataFrame({
    'nome': ['José da Silva', 'Yoda', 'Luke Skywalker'] ,
    'idade': [50, 100, 20] ,
    'peso': [70.3, 15.8, 60.5] ,
    'eh jedi': [False, True, True] # nomes nas colunas pode ter espaço
})

In [50]:
personagens_df

             nome  idade  peso  eh jedi
0   José da Silva     50  70.3    False
1            Yoda    100  15.8     True
2  Luke Skywalker     20  60.5     True

In [51]:
personagens_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     3 non-null      str
 1   idade    3 non-null      int64
 2   peso     3 non-null      float64
 3   eh jedi  3 non-null      bool
dtypes: bool(1), float64(1), int64(1), str(1)
memory usage: 207.0 bytes

## Renomeando as colunas de um DataFrame

O atributo DataFrame.columns retorna uma lista com os nomes de todas as colunas do data frame.

In [52]:
personagens_df.columns

Index(['nome', 'idade', 'peso', 'eh jedi'], dtype='str')

In [53]:
# converte para uma lista 
list(personagens_df.columns)

['nome', 'idade', 'peso', 'eh jedi']

===> Para renomear colunas do data frame, utilizamos o método DataFrame.rename, que retorna uma cópia do data frame com as colunas renomeadas:

In [54]:
personagens_df.rename(columns={
    'nome': 'Nome Completo',
    'idade': 'Idade',
    'peso': 'Peso',
    'eh jedi': 'Eh Jedi'
})

    Nome Completo  Idade  Peso  Eh Jedi
0   José da Silva     50  70.3    False
1            Yoda    100  15.8     True
2  Luke Skywalker     20  60.5     True

In [55]:
personagens_df

             nome  idade  peso  eh jedi
0   José da Silva     50  70.3    False
1            Yoda    100  15.8     True
2  Luke Skywalker     20  60.5     True

### para alterar os valores originais usamos inplace = True

In [56]:
personagens_df.rename(columns={
    'nome': 'Nome Completo',
    'idade': 'Idade',
    'peso': 'Peso',
    'eh jedi': 'Eh Jedi'
}, inplace = True)

In [57]:
personagens_df

    Nome Completo  Idade  Peso  Eh Jedi
0   José da Silva     50  70.3    False
1            Yoda    100  15.8     True
2  Luke Skywalker     20  60.5     True

### renomear todas as colunas de uma única vez

In [58]:
lista = [ x.upper() for x in list(personagens_df.columns) ]
personagens_df.columns = lista
personagens_df

    NOME COMPLETO  IDADE  PESO  EH JEDI
0   José da Silva     50  70.3    False
1            Yoda    100  15.8     True
2  Luke Skywalker     20  60.5     True

## Series

Uma Series é um array unidimensional com os dados e rótulos de um eixo do dataset.

In [59]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,DEFAULT
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,DEFAULT
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT

In [60]:
# selecionando uma coluna inteira
data['ESTADO']

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: str

In [22]:
# Selecionando uma coluna inteira de outra forma , acessando pelo ' . '
# ATENÇÃO -> Só funciona se não tiver espaços ou caracteres especiais, como acentos.
data.ESTADO

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: str

In [61]:
type(data['ESTADO'])

pandas.Series

In [62]:
# Selecionando a observação de uma linha do DataFrame
data.iloc[1]

DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
NOVA COLUNA                               DEFAULT
Name: 1, dtype: object

In [63]:
type(data.iloc[100])

pandas.Series

## Criando uma Series

Podemos criar um DataFrame a partir de uma lista de elementos.

In [64]:
pd.Series([5.4, 6, 9.9999])

0    5.4000
1    6.0000
2    9.9999
dtype: float64

### Alterando o nome dos indices e o nome da Series

In [65]:
pd.Series( [5.5, 6.3, 8.9], index=['Prova 1', 'Prova 2', 'Projeto Final'], name = 'Notas do Luke Skywalker' )

Prova 1          5.5
Prova 2          6.3
Projeto Final    8.9
Name: Notas do Luke Skywalker, dtype: float64

## Atribuindo Dados

In [66]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,DEFAULT
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,DEFAULT
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT

### Atribuindo constantes

In [67]:
produto_view_referencia = data['PRODUTO']
produto_view_referencia

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
120818     OLEO DIESEL S10
120819     OLEO DIESEL S10
120820     OLEO DIESEL S10
120821     OLEO DIESEL S10
120822     OLEO DIESEL S10
Name: PRODUTO, Length: 120823, dtype: str

Para fazer uma cópia é necessário passar o método copy() para esse data frame

In [69]:
produto_copia = data['PRODUTO'].copy()

In [68]:
produto_copia

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
120818     OLEO DIESEL S10
120819     OLEO DIESEL S10
120820     OLEO DIESEL S10
120821     OLEO DIESEL S10
120822     OLEO DIESEL S10
Name: PRODUTO, Length: 120823, dtype: str

### Atenção

Caso faça:
```bash
    produto = data['PRODUTO'] # produto é apenas referencia
    data['PRODUTO'] = 'Combustível' # altera todos os valores que estão em PRODUTO para Combustível
```
Temos que produto é apenas uma referencia , ou seja caso não queiramos alterar diretamente os valores de nosso data frame devemos fazer uma cópia do mesmo para uma nova variáveil usando o comando copy() não perdendo valores e preservando o data frame original.

### Atribuindo uma Series ou Lista de valores

In [70]:
# deve ser passar a mesma quantidade esperada de valores que já estão em nosso data frame
nLinhas, nColunas = data.shape
nLinhas, nColunas

(120823, 19)

In [71]:
novos_produtos = [ f'Produto {i}' for i in range(nLinhas) ]
len(novos_produtos)

120823

Agora vamos alterar e ver como fica o resultado

In [72]:
data['PRODUTO'] = novos_produtos
data['PRODUTO'].head()

0    Produto 0
1    Produto 1
2    Produto 2
3    Produto 3
4    Produto 4
Name: PRODUTO, dtype: str

Note que na nossa variável apenas de referência eles também foram copiados

In [73]:
produto_view_referencia

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
120818     OLEO DIESEL S10
120819     OLEO DIESEL S10
120820     OLEO DIESEL S10
120821     OLEO DIESEL S10
120822     OLEO DIESEL S10
Name: PRODUTO, Length: 120823, dtype: str

In [74]:
# comparando a referência com a cópia
print(produto_view_referencia)
print('\n')
print(produto_copia)

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
120818     OLEO DIESEL S10
120819     OLEO DIESEL S10
120820     OLEO DIESEL S10
120821     OLEO DIESEL S10
120822     OLEO DIESEL S10
Name: PRODUTO, Length: 120823, dtype: str


0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
120818     OLEO DIESEL S10
120819     OLEO DIESEL S10
120820     OLEO DIESEL S10
120821     OLEO DIESEL S10
120822     OLEO DIESEL S10
Name: PRODUTO, Length: 120823, dtype: str

Voltando aos valores padrões

In [75]:
data['PRODUTO'] = produto_copia
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,DEFAULT
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,DEFAULT
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT

## Criando novas colunas
Para criar uma nova coluna no data frame , atribuímos uma lista ou Series ou uma constante a uma nova chave no 'data frame'.   
A quantidade de valores da lista precisa ser igual ao número de linhas/registros do data frame

In [76]:
# criando uma nova coluna no data frame , como iremos fazer isso apenas para facilitar 
# irei criar uma cópia de nosso DataFrame original
data_copia = data.copy()
data_copia

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,DEFAULT
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,DEFAULT
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT

### Criando uma coluna a partir de um valor constante

In [77]:
data['NOVA COLUNA'] = 'DEFAULT'
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,DEFAULT
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,DEFAULT
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT

Ao criar o comando eu digitei duas vezes e com isso temos duas colunas novas, uma que se chama 'Nova Coluna' e outra que se chama 'NOVA COLUNA', com isso temos um produto semântico , que devemos resolver apagando uma das colunas novas usando o comando drop()

In [78]:
data = data.drop(columns=['Nova Coluna'])
data

KeyError: "['Nova Coluna'] not found in axis"

### Atribuindo intervalo de valores para uma nova coluna

In [79]:
data['INTERVALO DE VALORES'] = range(data.shape[0])
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,DEFAULT,2
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,DEFAULT,3
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,4.690,-99999.0,0.012,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120818
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,4.739,-99999.0,0.045,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120819
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,5.199,-99999.0,0.051,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120820
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,4.699,-99999.0,0.046,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120821
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,4.699,-99999.0,0.036,-99999.0,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120822

### Atribuindo uma Series a uma nova coluna no dataframe

In [80]:
# verificar se os valores são do mesmo tipo
print(data['PREÇO MÉDIO DISTRIBUIÇÃO'].dtypes)

# realizar a conversão para o tipo adequado
data['PREÇO MÉDIO DISTRIBUIÇÃO'] = pd.to_numeric(data['PREÇO MÉDIO DISTRIBUIÇÃO'], errors='coerce')

data['PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR'] = data['PREÇO MÉDIO DISTRIBUIÇÃO'] * 5.10
data

str

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0,4.2075
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1,3.8913
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,DEFAULT,2,4.9470
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,DEFAULT,3,4.2330
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4,4.7991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120818,2021-04-25,2021-05-01,NORTE,RORAIMA,OLEO DIESEL S10,12,R$/l,4.582,0.056,4.510,...,-99999.0,0.012,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120818,-509994.9000
120819,2021-04-25,2021-05-01,SUL,SANTA CATARINA,OLEO DIESEL S10,100,R$/l,4.141,0.187,3.838,...,-99999.0,0.045,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120819,-509994.9000
120820,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,OLEO DIESEL S10,886,R$/l,4.246,0.216,3.769,...,-99999.0,0.051,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120820,-509994.9000
120821,2021-04-25,2021-05-01,NORDESTE,SERGIPE,OLEO DIESEL S10,33,R$/l,4.464,0.205,4.190,...,-99999.0,0.046,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120821,-509994.9000
120822,2021-04-25,2021-05-01,NORTE,TOCANTINS,OLEO DIESEL S10,18,R$/l,4.352,0.156,4.199,...,-99999.0,0.036,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,DEFAULT,120822,-509994.9000

## Índices

Todo dataframe possui índices que não são considerados colunas da tabela. Eles podem ser numéricos indo de zero até quantidade de linha menos um , mas também podem ser do tipo textual (rótulos / labels)

In [81]:
data.index

RangeIndex(start=0, stop=120823, step=1)

In [82]:
# criar uma lista a partir do data.index
lista = list(data.index) 
# ou 
lista = data.index.to_list()
len(lista)

120823

### Exemplo de DataFrame com índices textuais ( labels )

In [83]:
pesquisa_de_satisfacao = pd.DataFrame({
    'bom': [50, 21, 100],
    'ruim': [131, 2, 30], 
    'pessimo': [30, 20, 1]
}, index = ['XboxOne', 'Playstation4', 'Switch'])
pesquisa_de_satisfacao

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

### Selecionando uma ou mais observações (Indexação)

In [84]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0,4.2075
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1,3.8913
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,DEFAULT,2,4.9470
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,DEFAULT,3,4.2330
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4,4.7991

## ==> index based selection (Seleção baseada em índices)
iloc -> seleciona elementos do DataFrame, baseado em seu índice , sendo primeiro a linha e depois a coluna

#### Selecionando uma observação / registro / linha

In [86]:
data.iloc[1]

DATA INICIAL                               2004-05-09
DATA FINAL                                 2004-05-15
REGIÃO                                   CENTRO OESTE
ESTADO                                          GOIAS
PRODUTO                              ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                      387
UNIDADE DE MEDIDA                                R$/l
PREÇO MÉDIO REVENDA                             1.162
DESVIO PADRÃO REVENDA                           0.114
PREÇO MÍNIMO REVENDA                             0.89
PREÇO MÁXIMO REVENDA                            1.449
MARGEM MÉDIA REVENDA                            0.399
COEF DE VARIAÇÃO REVENDA                        0.098
PREÇO MÉDIO DISTRIBUIÇÃO                        0.763
DESVIO PADRÃO DISTRIBUIÇÃO                      0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                      0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                        1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO                   0.115
NOVA COLUNA                                   DEFAULT
INTERVALO DE VALORES                                1
PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR              3.8913
Name: 1, dtype: object

Mostra a amostra na linha 1 ou registro 1

### Selecionando múltiplas observações / linhas contínuas

In [87]:
# selecionando as linhas de 0 a 5 inclusive
data.iloc[:6,] # é o usado a técnica do slice do python não precisa colocar o zero pois é o primeiro índice

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0,4.2075
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1,3.8913
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,DEFAULT,2,4.9470
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,DEFAULT,3,4.2330
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4,4.7991
5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,0.999,...,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,DEFAULT,5,4.8807

### Selecionando itens de uma lista de indices

In [88]:
data.iloc[[1,3,5,7,9]]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1,3.8913
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,DEFAULT,3,4.2330
5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,0.999,...,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,DEFAULT,5,4.8807
7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,1.350,...,0.515,0.097,1.116,0.091,0.9923,1.36183,0.082,DEFAULT,7,5.6916
9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,0.989,...,0.277,0.115,0.947,0.091,0.5643,1.3541,0.096,DEFAULT,9,4.8297

### Selecionando itens usando uma função lambda

In [89]:
data.iloc[lambda x: (x.index % 2 == 0) & (x.index < 10)]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0,4.2075
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,DEFAULT,2,4.9470
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4,4.7991
6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,1.03,...,0.353,0.150,1.100,0.068,0.7332,1.294,0.062,DEFAULT,6,5.6100
8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,1.10,...,0.353,0.101,0.931,0.072,0.7577,1.2972,0.077,DEFAULT,8,4.7481

### Retornando uma  linha e coluna ( linha == 1 , coluna == 3)

In [91]:
data.iloc[1,3]

'GOIAS'

## ==> label based selection (Seleção baseada em rótulos)
loc faz a seleção dos elementos do Dataframe, baseaso em rótulos --> row-first, column-second

In [92]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [93]:
# usando o método loc -> retorna a linha cujo índice é XboxOne
pesquisa_de_satisfacao.loc['XboxOne']

bom         50
ruim       131
pessimo     30
Name: XboxOne, dtype: int64

### Não funciona
iloc -> acessar índices com rótulos

In [94]:
pesquisa_de_satisfacao.iloc['XboxOne']

TypeError: Cannot index by location index with a non-integer key

### Não funciona
loc acessar índices

In [95]:
pesquisa_de_satisfacao.loc[0]

KeyError: 0

### Acessar dados usando iloc e loc dentro do Dataframe

In [96]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

### pessoas que acharam o Playstation4 ruim

In [97]:
pesquisa_de_satisfacao.loc['Playstation4','ruim']

np.int64(2)

### sub tabela do Dataframe

In [98]:
pesquisa_de_satisfacao.loc[['Switch', 'XboxOne']]

         bom  ruim  pessimo
Switch   100    30        1
XboxOne   50   131       30

### todas as linhas onde o produto é considerado ruim, péssimo

In [99]:
pesquisa_de_satisfacao.loc[:, ['ruim', 'pessimo']]

              ruim  pessimo
XboxOne        131       30
Playstation4     2       20
Switch          30        1

## Observação
**Índices Númericos** por default, possuem rótulos que correspondem aos seus valores

In [101]:
data.loc[100]

DATA INICIAL                               2004-05-30
DATA FINAL                                 2004-06-05
REGIÃO                                          NORTE
ESTADO                                      TOCANTINS
PRODUTO                              ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                       73
UNIDADE DE MEDIDA                                R$/l
PREÇO MÉDIO REVENDA                             1.268
DESVIO PADRÃO REVENDA                           0.101
PREÇO MÍNIMO REVENDA                            1.099
PREÇO MÁXIMO REVENDA                             1.58
MARGEM MÉDIA REVENDA                            0.572
COEF DE VARIAÇÃO REVENDA                         0.08
PREÇO MÉDIO DISTRIBUIÇÃO                        0.696
DESVIO PADRÃO DISTRIBUIÇÃO                      0.102
PREÇO MÍNIMO DISTRIBUIÇÃO                       0.554
PREÇO MÁXIMO DISTRIBUIÇÃO                      0.9612
COEF DE VARIAÇÃO DISTRIBUIÇÃO                   0.147
NOVA COLUNA                                   DEFAULT
INTERVALO DE VALORES                              100
PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR              3.5496
Name: 100, dtype: object

## Selecionando um ou mais atributos ( colunas )

In [102]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0,4.2075
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1,3.8913
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,DEFAULT,2,4.9470
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,DEFAULT,3,4.2330
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4,4.7991

In [103]:
data['ESTADO']

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: str

In [104]:
data.ESTADO

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: str

In [47]:
data.loc[:, ['ESTADO']]

                    ESTADO
0         DISTRITO FEDERAL
1                    GOIAS
2              MATO GROSSO
3       MATO GROSSO DO SUL
4                  ALAGOAS
...                    ...
120818             RORAIMA
120819      SANTA CATARINA
120820           SAO PAULO
120821             SERGIPE
120822           TOCANTINS

[120823 rows x 1 columns]

### Atenção
O acesso a uma coluna utilizando o nome_da_coluna, só funciona se não tiver caracteres considerados inválidos, tais como espaço, acentuação, c cedilha, etc..
Nesse caso devemos usar apenas a seleção via string

In [105]:
data['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: str

### Selecionando múltiplas colunas

In [106]:
data[['PRODUTO', 'ESTADO', 'REGIÃO']]

                 PRODUTO              ESTADO        REGIÃO
0       ETANOL HIDRATADO    DISTRITO FEDERAL  CENTRO OESTE
1       ETANOL HIDRATADO               GOIAS  CENTRO OESTE
2       ETANOL HIDRATADO         MATO GROSSO  CENTRO OESTE
3       ETANOL HIDRATADO  MATO GROSSO DO SUL  CENTRO OESTE
4       ETANOL HIDRATADO             ALAGOAS      NORDESTE
...                  ...                 ...           ...
120818   OLEO DIESEL S10             RORAIMA         NORTE
120819   OLEO DIESEL S10      SANTA CATARINA           SUL
120820   OLEO DIESEL S10           SAO PAULO       SUDESTE
120821   OLEO DIESEL S10             SERGIPE      NORDESTE
120822   OLEO DIESEL S10           TOCANTINS         NORTE

[120823 rows x 3 columns]

## ==> Label-based selection ( seleção baseada em rótulos )

loc: seleciona os elementos do dataframe baseado em seus rótulos --> row first, column-second

In [107]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [108]:
# retorna a linha de índice 0 (implícito) --> usando o iloc
pesquisa_de_satisfacao.iloc[0]

bom         50
ruim       131
pessimo     30
Name: XboxOne, dtype: int64

In [110]:
# retorna o valor da linha de início 0 ( implícito ) e coluna de indíce 1 ( implicito ) --> usando o iloc
pesquisa_de_satisfacao.iloc[0 ,1]

np.int64(131)

In [111]:
# retorna a linha cujo o rótulo do índice é XboxOne
pesquisa_de_satisfacao.loc['XboxOne']

bom         50
ruim       131
pessimo     30
Name: XboxOne, dtype: int64

In [112]:
# Não funciona 
pesquisa_de_satisfacao.iloc['XboxOne']

TypeError: Cannot index by location index with a non-integer key

In [113]:
# Não funciona -- loc tetando acessar o indice
pesquisa_de_satisfacao.loc[0]

KeyError: 0

In [114]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [115]:
# mostra a quantidade de dados da pesquisa para uma determinada linha e coluna
pesquisa_de_satisfacao.loc['Playstation4', 'pessimo']

np.int64(20)

In [116]:
# selecionando as linhas de índice rotulados XboxOne, Switch
pesquisa_de_satisfacao.loc[['XboxOne','Switch']]

         bom  ruim  pessimo
XboxOne   50   131       30
Switch   100    30        1

In [117]:
# retorna todas as linhas e apenas as colunas com rótulos 'bom' e 'ruim'
pesquisa_de_satisfacao.loc[:,['bom','ruim']]

              bom  ruim
XboxOne        50   131
Playstation4   21     2
Switch        100    30

## Selecionando um ou mais atributos ( colunas )

In [118]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0,4.2075
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1,3.8913
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,DEFAULT,2,4.9470
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,DEFAULT,3,4.2330
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4,4.7991

In [119]:
# retornando a coluna/ atributo 'ESTADO'
data['ESTADO']

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: str

In [121]:
data.ESTADO

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: str

In [122]:
data.loc[:, 'ESTADO']

0           DISTRITO FEDERAL
1                      GOIAS
2                MATO GROSSO
3         MATO GROSSO DO SUL
4                    ALAGOAS
                 ...
120818               RORAIMA
120819        SANTA CATARINA
120820             SAO PAULO
120821               SERGIPE
120822             TOCANTINS
Name: ESTADO, Length: 120823, dtype: str

In [124]:
 ### Atenção:
 #   No caso de strings com acentuação , espaços, caracteres especiais , não tem como acessar utilizando 
# diretamente o método ponto.
data.DATA INICIAL

SyntaxError: invalid syntax (619901935.py, line 4)

In [125]:
# Para esses casos iremos utilizar sempre a passagem da string 
data['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
120818    2021-04-25
120819    2021-04-25
120820    2021-04-25
120821    2021-04-25
120822    2021-04-25
Name: DATA INICIAL, Length: 120823, dtype: str

In [127]:
# selecionando múltiplas colunas
data[['PRODUTO','ESTADO','REGIÃO']]

                 PRODUTO              ESTADO        REGIÃO
0       ETANOL HIDRATADO    DISTRITO FEDERAL  CENTRO OESTE
1       ETANOL HIDRATADO               GOIAS  CENTRO OESTE
2       ETANOL HIDRATADO         MATO GROSSO  CENTRO OESTE
3       ETANOL HIDRATADO  MATO GROSSO DO SUL  CENTRO OESTE
4       ETANOL HIDRATADO             ALAGOAS      NORDESTE
...                  ...                 ...           ...
120818   OLEO DIESEL S10             RORAIMA         NORTE
120819   OLEO DIESEL S10      SANTA CATARINA           SUL
120820   OLEO DIESEL S10           SAO PAULO       SUDESTE
120821   OLEO DIESEL S10             SERGIPE      NORDESTE
120822   OLEO DIESEL S10           TOCANTINS         NORTE

[120823 rows x 3 columns]

## Removendo um Atributo (Coluna) do Data Frame

In [140]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,NOVA COLUNA,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,DEFAULT,0,4.2075
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,DEFAULT,1,3.8913
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,DEFAULT,2,4.9470
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,DEFAULT,3,4.2330
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,DEFAULT,4,4.7991

Vamos remover do nosso data set a coluna 'NOVA COLUNA', pois tem apenas valores DEFAULT.

### Deleta / remove in-place ( ou seja no próprio dataframe ) a coluna de rótulo 'NOVA COLUNA'

In [142]:
del data['NOVA COLUNA']

In [143]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES,PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,0,4.2075
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,1,3.8913
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,2,4.9470
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,3,4.2330
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,4,4.7991

<br> Removendo a coluna 'PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR' </br>

In [145]:
del data['PREÇO MÉDIO DISTRIBUIÇÃO EM DÓLAR']
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,0
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,1
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,2
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,3
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,4

## Salvando um Data Frame
Para salvar um Data Frame , usamos o método __.to_csv__.
Por padrão, esse método __salva os índices das tabelas como uma coluna no CSV.__
Por padrão, o método utilizará, ',' como separador das colunas. Caso queira alterá-lo, utilize o parâmetro sep.

In [146]:
data.to_csv('./datasets/precosCombustiveis.csv', index=False)

### salvando com índice igual a True

In [148]:
data.to_csv('./datasets/precosCombustiveisComIndiceIgualATrue.csv', index=True)

## Seleção condicional: Filtrando amostras
Existem algumas maneiras de filtrarmos os dados de nossa amostra.
Mas primeiro vamos carregar os dados salvos anteriormente.

In [150]:
data = pd.read_csv('./datasets/precosCombustiveis.csv')

In [152]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,0
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,1
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,2
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,3
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,4

In [153]:
# mostra valores únicos de uma coluna de nosso dataset
data['ESTADO'].unique()

<StringArray>
[   'DISTRITO FEDERAL',               'GOIAS',         'MATO GROSSO',
  'MATO GROSSO DO SUL',             'ALAGOAS',               'BAHIA',
               'CEARA',            'MARANHAO',             'PARAIBA',
          'PERNAMBUCO',               'PIAUI', 'RIO GRANDE DO NORTE',
             'SERGIPE',                'ACRE',               'AMAPA',
            'AMAZONAS',                'PARA',            'RONDONIA',
             'RORAIMA',           'TOCANTINS',      'ESPIRITO SANTO',
        'MINAS GERAIS',      'RIO DE JANEIRO',           'SAO PAULO',
              'PARANA',   'RIO GRANDE DO SUL',      'SANTA CATARINA']
Length: 27, dtype: str

### Selecionando apenas os preços dos Postos do 'RIO GRANDE DO SUL'

### ===> 1- Usando seleção condicional ( Comparações diretas )
O código abaixo retorna a Series (' array ') com o número de linhas ( observações ) do Data Frame , que informa o registro de preços dos postos do estado do RIO GRANDE DO SUL ( TRUE )

In [155]:
# Faz a comparação elemento a elemento da SERIES retornando uma Series de booleans
data['ESTADO'] == 'RIO GRANDE DO SUL'

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Name: ESTADO, Length: 120823, dtype: bool

In [157]:
# Salvando a series de booleans na variável selecao
selecao = data['ESTADO'] == 'RIO GRANDE DO SUL'

In [159]:
# mostra apenas os últimos dados
print(selecao.tail())
# mostra o tipo de dado
print(type(selecao))
# mostra a quantidade de linhas
print(selecao.shape)
# mostra a mesma quantidade para fins de comparação
print(data.shape)

120818    False
120819    False
120820    False
120821    False
120822    False
Name: ESTADO, dtype: bool
<class 'pandas.Series'>
(120823,)
(120823, 19)

Filtrando os postos do estado do RIO GRANDE DO SUL

In [161]:
# mostra apenas os dados verdadeiros que correspondem a selecao 
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
25,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.710,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
52,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.710,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
79,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.710,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
106,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.710,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
133,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.710,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120719,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,187,R$/l,5.781,0.196,5.599,6.663,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120719
120746,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GLP,189,R$/13Kg,82.370,4.658,73.000,95.000,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120746
120765,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GNV,14,R$/m3,4.369,0.080,4.269,4.499,-99999.0,0.018,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120765
120789,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL,111,R$/l,4.079,0.191,3.795,4.695,-99999.0,0.047,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120789
120816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120816

O resultado é um Data Frame com apenas os registros filtrados através da variável selecao.

Podemos ainda utilizar o método __loc__ com o mesmo fim.

In [162]:
data.loc[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
25,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.710,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
52,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.710,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
79,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.710,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
106,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.710,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
133,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.710,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120719,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,187,R$/l,5.781,0.196,5.599,6.663,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120719
120746,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GLP,189,R$/13Kg,82.370,4.658,73.000,95.000,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120746
120765,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GNV,14,R$/m3,4.369,0.080,4.269,4.499,-99999.0,0.018,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120765
120789,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL,111,R$/l,4.079,0.191,3.795,4.695,-99999.0,0.047,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120789
120816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120816

Também podemos utilizar o formato abaixo para obtermos o mesmo resultado, nesse caso não guardamos o valor do Data Frame em uma variável, mostrando diretamente os dados, entretanto dessa forma não iremos poder trabalhar com a variável selecao

In [167]:
data[data['ESTADO'] == 'RIO GRANDE DO SUL'].head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
25,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.71,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
52,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.71,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
79,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.71,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
106,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.71,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
133,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.71,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133

### ===> 2- Usando o método Query 
Query filtra linhas de um DataFrame baseado em query ( pergunta ).

In [168]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,0
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,1
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,2
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,3
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,4

In [174]:
data.query('ESTADO == "RIO GRANDE DO SUL"')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
25,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.710,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
52,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.710,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
79,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.710,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
106,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.710,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
133,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.710,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120719,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,187,R$/l,5.781,0.196,5.599,6.663,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120719
120746,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GLP,189,R$/13Kg,82.370,4.658,73.000,95.000,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120746
120765,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GNV,14,R$/m3,4.369,0.080,4.269,4.499,-99999.0,0.018,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120765
120789,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL,111,R$/l,4.079,0.191,3.795,4.695,-99999.0,0.047,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120789
120816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120816

### Atenção:
Uma boa prática ao investigarmos os dados é salvar em uma varíavel

In [177]:
# salva em memória na variável postos_RS
postos_RS = data.query('ESTADO == "RIO GRANDE DO SUL" ')

In [176]:
postos_RS.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
25,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.71,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
52,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.71,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
79,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.71,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
106,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.71,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
133,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.71,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133

### Reset dos índices do Data Frame original
Algumas vezes precisamos dar um reset no índice , ou seja iniciar novamente do zero, devemos analisar quando isso é necessário, talvez quando queremos um novo subset ou salvar apenas os dados daquele ESTADO em um novo csv.
Usamos o método .reset_index() que não altera a nossa variável

In [186]:
postos_RS.reset_index()

,index,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,0,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.710,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
1,1,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.710,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
2,2,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.710,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
3,3,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.710,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
4,4,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.710,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4814,4814,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,187,R$/l,5.781,0.196,5.599,6.663,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120719
4815,4815,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GLP,189,R$/13Kg,82.370,4.658,73.000,95.000,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120746
4816,4816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GNV,14,R$/m3,4.369,0.080,4.269,4.499,-99999.0,0.018,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120765
4817,4817,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL,111,R$/l,4.079,0.191,3.795,4.695,-99999.0,0.047,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120789
4818,4818,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120816

Podemos notar que nossa primeira linha corresponde a um novo índice aquele que foi criado usando o método .reset_index(), entretanto ainda temos na nossa variável o índice original , caso não queiramos isso , podemos passar o parâmetro drop.

In [180]:
postos_RS.reset_index(drop=True)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.710,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
1,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.710,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
2,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.710,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
3,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.710,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
4,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.710,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4814,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,187,R$/l,5.781,0.196,5.599,6.663,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120719
4815,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GLP,189,R$/13Kg,82.370,4.658,73.000,95.000,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120746
4816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GNV,14,R$/m3,4.369,0.080,4.269,4.499,-99999.0,0.018,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120765
4817,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL,111,R$/l,4.079,0.191,3.795,4.695,-99999.0,0.047,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120789
4818,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120816

Os dados de postos_RS ainda não foram alterados , visto que o resultado é apenas uma cópia, para realizarmos a alteração definitiva da variável , devemos recorrer ao in place.

In [185]:
# postos do RIO GRANDE DO SUL, sem alteração
postos_RS.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.71,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
1,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.71,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
2,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.71,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
3,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.71,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
4,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.71,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133

In [190]:
postos_RS.reset_index(drop=True, inplace=True)

In [192]:
postos_RS

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.710,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
1,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.710,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
2,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.710,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
3,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.710,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
4,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.710,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4814,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GASOLINA COMUM,187,R$/l,5.781,0.196,5.599,6.663,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120719
4815,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GLP,189,R$/13Kg,82.370,4.658,73.000,95.000,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120746
4816,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,GNV,14,R$/m3,4.369,0.080,4.269,4.499,-99999.0,0.018,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120765
4817,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL,111,R$/l,4.079,0.191,3.795,4.695,-99999.0,0.047,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120789
4818,2021-04-25,2021-05-01,SUL,RIO GRANDE DO SUL,OLEO DIESEL S10,148,R$/l,4.140,0.236,3.849,4.949,-99999.0,0.057,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120816

### ===> 3- Fazendo tudo em apenas uma linha (single line code).

In [210]:
postos_RS = data.query('ESTADO == "RIO GRANDE DO SUL"').reset_index(drop=True, inplace=False)

In [211]:
postos_RS.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,689,R$/l,1.224,0.143,0.880,1.71,0.332,0.117,0.892,0.09,0.644,1.2727,0.101,25
1,2004-05-16,2004-05-22,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,674,R$/l,1.220,0.142,0.898,1.71,0.324,0.116,0.896,0.088,0.644,1.2378,0.098,52
2,2004-05-23,2004-05-29,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,690,R$/l,1.235,0.129,0.938,1.71,0.337,0.104,0.898,0.089,0.616,1.2727,0.099,79
3,2004-05-30,2004-06-05,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,686,R$/l,1.333,0.136,0.970,1.71,0.392,0.102,0.941,0.111,0.55,1.33,0.118,106
4,2004-06-06,2004-06-12,SUL,RIO GRANDE DO SUL,ETANOL HIDRATADO,698,R$/l,1.358,0.128,1.040,1.71,0.36,0.094,0.998,0.126,0.55,1.34,0.126,133

### Selecionando registros de postos do Rio de Janeiro com preços acima de 2 reais.

In [212]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,0
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,1
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,2
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,3
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,4

In [213]:
data["ESTADO"].unique()

<StringArray>
[   'DISTRITO FEDERAL',               'GOIAS',         'MATO GROSSO',
  'MATO GROSSO DO SUL',             'ALAGOAS',               'BAHIA',
               'CEARA',            'MARANHAO',             'PARAIBA',
          'PERNAMBUCO',               'PIAUI', 'RIO GRANDE DO NORTE',
             'SERGIPE',                'ACRE',               'AMAPA',
            'AMAZONAS',                'PARA',            'RONDONIA',
             'RORAIMA',           'TOCANTINS',      'ESPIRITO SANTO',
        'MINAS GERAIS',      'RIO DE JANEIRO',           'SAO PAULO',
              'PARANA',   'RIO GRANDE DO SUL',      'SANTA CATARINA']
Length: 27, dtype: str

In [214]:
data['ESTADO'] == 'RIO DE JANEIRO'

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Name: ESTADO, Length: 120823, dtype: bool

In [215]:
data['PREÇO MÉDIO REVENDA'] > 2.0

0         False
1         False
2         False
3         False
4         False
          ...
120818     True
120819     True
120820     True
120821     True
120822     True
Name: PREÇO MÉDIO REVENDA, Length: 120823, dtype: bool

In [217]:
selecao = (data['ESTADO'] == 'RIO DE JANEIRO') & (data['PREÇO MÉDIO REVENDA'] > 2.0)

### Atenção:
Note que o __AND__ em python para o pandas é o __&__ , o __OR__ é o __|__ e o NOT é o __~__

In [219]:
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061,2501
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064,2528
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071,2555
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072,2582
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068,2609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120717
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120744
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120763
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120787
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120814

Podemos usar o método __.query()__ mas o mesmo não irá funcionar nessa caso pois o rótulo ( PREÇO MÉDIO DE REVENDA ), possui caracteres inválidos o **ç** e o **´**.
Vamos mostrar um exemplo abaixo usando o método .query() para um caso sem problemas, por exemplo no rótulo ( UNIDADE DE MEDIDA ).

In [231]:
postos_vendem_gas_RJ = data.query('ESTADO == "RIO DE JANEIRO" and (PRODUTO == "GNV" or PRODUTO == "GLP")')

In [232]:
postos_vendem_gas_RJ

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
24154,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GLP,385,R$/13Kg,29.154,1.426,25.000,33.900,4.564,0.049,24.590,1.322,22,29,0.054,24154
24181,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GLP,407,R$/13Kg,29.138,1.510,25.000,33.900,4.938,0.052,24.200,1.491,21,29,0.062,24181
24208,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GLP,409,R$/13Kg,28.997,1.445,25.000,35.000,4.473,0.050,24.524,1.417,20.5,28.11,0.058,24208
24235,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GLP,422,R$/13Kg,29.034,1.527,24.990,35.000,4.757,0.053,24.277,1.263,21,28,0.052,24235
24262,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GLP,405,R$/13Kg,29.108,1.502,25.000,35.000,4.707,0.052,24.401,1.262,21,28,0.052,24262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120407,2021-04-11,2021-04-17,SUDESTE,RIO DE JANEIRO,GNV,101,R$/m3,3.152,0.371,2.759,4.399,-99999.0,0.118,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120407
120565,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GLP,138,R$/13Kg,75.651,6.054,66.000,93.000,-99999.0,0.080,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120565
120585,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GNV,101,R$/m3,3.132,0.325,2.779,4.399,-99999.0,0.104,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120585
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120744
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120763

Caso o Data Frame seja muito grande a abordagem deverá ser feita em partes para diminuir a lentidão da query().

In [234]:
apenas_estado_rj = data['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = data[apenas_estado_rj]
postos_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22,22
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217,49
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202,76
103,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,955,R$/l,1.149,0.156,0.799,1.599,0.3,0.136,0.849,0.188,0.3453,1.3667,0.221,103
130,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,966,R$/l,1.165,0.154,0.830,1.599,0.254,0.132,0.911,0.198,0.4,1.3667,0.217,130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120717
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120744
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120763
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120787
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120814

In [237]:
preco_medio = postos_rj['PREÇO MÉDIO REVENDA'] > 2
preco_medio

22        False
49        False
76        False
103       False
130       False
          ...
120717     True
120744     True
120763     True
120787     True
120814     True
Name: PREÇO MÉDIO REVENDA, Length: 4819, dtype: bool

In [239]:
postos_rj_maior_2 = postos_rj[preco_medio]
postos_rj_maior_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061,2501
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064,2528
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071,2555
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072,2582
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068,2609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120717
120744,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GLP,137,R$/13Kg,75.218,5.398,65.000,93.000,-99999.0,0.072,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120744
120763,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GNV,77,R$/m3,3.011,0.385,2.759,4.399,-99999.0,0.128,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120763
120787,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL,72,R$/l,4.290,0.183,3.849,4.599,-99999.0,0.043,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120787
120814,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,OLEO DIESEL S10,155,R$/l,4.302,0.172,3.930,4.699,-99999.0,0.040,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120814

### Selecionando registros de postos de São Paulo ou do Rio de Janeiro com Gasolina comum acima de 2 reais
Podemos fazer uma solução 'mais lenta' , percorrendo o DataFrame inteiro múltiplas vezes.

In [241]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,0
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,1
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.970,0.095,0.5614,1.161,0.098,2
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,3
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,4

In [251]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
selecao_1
selecao_2 = (data['PRODUTO'] == 'GASOLINA COMUM')
selecao_2
selecao_3 = (data['PREÇO MÉDIO REVENDA'] > 2)
selecao_3
selecao_final = selecao_1 & selecao_2 & selecao_3
selecao_final

0         False
1         False
2         False
3         False
4         False
          ...
120818    False
120819    False
120820    False
120821    False
120822    False
Length: 120823, dtype: bool

In [252]:
data[selecao_final]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,12086
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,12113
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,2.599,0.252,0.053,1.790,0.046,1.63596,2.2137,0.026,12140
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,2.599,0.251,0.054,1.802,0.055,1.64,2.21425,0.031,12167
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,2.599,0.247,0.052,1.816,0.054,1.64,2.32425,0.03,12194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120366,2021-04-11,2021-04-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1058,R$/l,5.206,0.234,3.899,5.999,-99999.0,0.045,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120366
120538,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,240,R$/l,6.071,0.217,5.399,6.599,-99999.0,0.036,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120538
120544,2021-04-18,2021-04-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1075,R$/l,5.205,0.216,4.199,5.999,-99999.0,0.041,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120544
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120717
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120723

In [255]:
data_filtrado = data[selecao_final]
print(data_filtrado.ESTADO.unique())
print(data_filtrado.PRODUTO.unique())

<StringArray>
['RIO DE JANEIRO', 'SAO PAULO']
Length: 2, dtype: str
<StringArray>
['GASOLINA COMUM']
Length: 1, dtype: str

### Maneira mais rápida de fazer

In [258]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
# apenas postos de rj e sp
postos_sp_rj = data[selecao_1]
selecao_2 = (postos_sp_rj['PRODUTO'] == 'GASOLINA COMUM')
selecao_2
postos_sp_rj_gasolina = postos_sp_rj[selecao_2]
# apenas produtos de sp ou rj que são gasolina comum 
postos_sp_rj_gasolina

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,12086
12087,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,2.399,0.235,0.053,1.656,0.064,1.38,1.944,0.039,12087
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,12113
12114,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,2.220,0.233,0.053,1.655,0.063,1.38,1.9319,0.038,12114
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,2.599,0.252,0.053,1.790,0.046,1.63596,2.2137,0.026,12140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120366,2021-04-11,2021-04-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1058,R$/l,5.206,0.234,3.899,5.999,-99999.0,0.045,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120366
120538,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,240,R$/l,6.071,0.217,5.399,6.599,-99999.0,0.036,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120538
120544,2021-04-18,2021-04-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1075,R$/l,5.205,0.216,4.199,5.999,-99999.0,0.041,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120544
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120717
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120723

In [259]:
selecao_3 = postos_sp_rj_gasolina['PREÇO MÉDIO REVENDA'] > 2
postos_sp_rj_gasolina_maior_2 = postos_sp_rj_gasolina[selecao_3]
postos_sp_rj_gasolina_maior_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,INTERVALO DE VALORES
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,12086
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,12113
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,2.599,0.252,0.053,1.790,0.046,1.63596,2.2137,0.026,12140
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,2.599,0.251,0.054,1.802,0.055,1.64,2.21425,0.031,12167
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,2.599,0.247,0.052,1.816,0.054,1.64,2.32425,0.03,12194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120366,2021-04-11,2021-04-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1058,R$/l,5.206,0.234,3.899,5.999,-99999.0,0.045,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120366
120538,2021-04-18,2021-04-24,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,240,R$/l,6.071,0.217,5.399,6.599,-99999.0,0.036,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120538
120544,2021-04-18,2021-04-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1075,R$/l,5.205,0.216,4.199,5.999,-99999.0,0.041,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120544
120717,2021-04-25,2021-05-01,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,198,R$/l,6.099,0.208,5.480,6.599,-99999.0,0.034,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120717
120723,2021-04-25,2021-05-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1187,R$/l,5.265,0.218,4.279,6.099,-99999.0,0.041,-99999.000,-99999.0,-99999.0,-99999.0,-99999.0,120723